### ISSUE TITLE
Not working with latest update of bagisto

### ISSUE THREAD

**Issue by shaizy1234** [codenteq/stripe-payment-gateway#9]
Hello,

I have tried your plugin with latest update and its giving error and not working, could you please check 

---
name: "🐛 Bug Report"
about: 'Report a general issue.'
---

# Bug Report

**Comment by ahmetarsiv** [comment]
@shaizy1234 Do you please support your error message with screenshots and scenarios you receive?

Best regards,

**Comment by shaizy1234** [comment]
its all default Bagisto latest version, did you test your plugin with new update of Bagisto?
